"""Emit a predictions.parquet whose 'signal' is 20-day median turnover.

    uv run python scripts/make_turnover_signal.py \
        --panel data/panels_bhav/oos_r4_pit_long.parquet \
        --like data/signal/r4_pit_long --out-tag turnover_long

WHY. `audit/S4_NULL_CONTROL.md` established that R4's signal does not beat a
random one out of sample (13 of 15 matched pairs to random), while the
*machinery* -- concentrating to ~30 names with a 1% no-trade band and a
volatility stop -- roughly halves drawdown against equal-weight and survives on
unseen data. The surviving result is portfolio construction, not alpha.

But "random" is not something anyone runs. Testing the surviving rule forward
needs a real selection, and this is the one chosen for it: the most liquid
names. It is transparent, it is not fitted to any outcome, and it is the
obvious choice a person would make without a model.

The output is deliberately shaped exactly like a signal artefact so the
allocator, the null control and the gate all consume it unchanged -- the point
is to compare like with like, not to build a second pipeline.

SUPPORT MASKING. Rows are restricted to the (date, ticker) pairs the reference
artefact scored. R4's predictions are OOS-only and tradeable-only, so a dense
turnover signal would hand this arm a larger, differently-shaped candidate set
than the arms it is compared against, and the comparison would price the
universe rather than the selection.
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import polars as pl

TURNOVER_COL = "dollar_volume_20"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel", required=True, type=Path)
    ap.add_argument("--like", required=True, type=Path,
                    help="reference signal dir; its (date,ticker) support "
                         "and index.json are reused")
    ap.add_argument("--out-tag", required=True)
    ap.add_argument("--out-root", type=Path, default=Path("data/signal"))
    a = ap.parse_args()

    ref = pl.read_parquet(a.like / "predictions.parquet").select(["date", "ticker"])
    panel = (
        pl.scan_parquet(a.panel)
        .select(["date", "ticker", "is_tradeable", TURNOVER_COL])
        .collect()
    )
    df = ref.join(panel, on=["date", "ticker"], how="inner").filter(pl.col("is_tradeable"))
    if df.height == 0:
        raise SystemExit("no overlapping tradeable rows between panel and reference support")

    # Per-date rank, so the scale matches a signal's and ties break the way the
    # allocator's top-K already expects. Higher turnover -> higher score.
    out = (
        df.with_columns(
            (pl.col(TURNOVER_COL).rank("average").over("date")
             / pl.len().over("date")).alias("r")
        )
        .select(
            "date", "ticker",
            pl.col("r").alias("r_hat_5d"),
            pl.col("r").alias("r_hat_20d"),
        )
        .sort(["date", "ticker"])
    )

    dest = a.out_root / a.out_tag
    dest.mkdir(parents=True, exist_ok=True)
    out.write_parquet(dest / "predictions.parquet")

    # Carry the reference index/summary so downstream loaders find what they
    # expect; overwrite the note so nobody mistakes this for a trained model.
    for name in ("index.json", "summary.json"):
        src = a.like / name
        if src.exists():
            shutil.copy(src, dest / name)
    idx_path = dest / "index.json"
    if idx_path.exists():
        idx = json.loads(idx_path.read_text())
        idx["note"] = (
            f"NOT A TRAINED MODEL. r_hat is the per-date cross-sectional rank of "
            f"{TURNOVER_COL}, generated by scripts/make_turnover_signal.py from "
            f"{a.panel}. No fitting of any kind."
        )
        idx_path.write_text(json.dumps(idx, indent=2))

    print(f"{dest/'predictions.parquet'}: {out.height:,} rows, "
          f"{out['date'].n_unique():,} dates, {out['ticker'].n_unique():,} tickers, "
          f"{out['date'].min()}..{out['date'].max()}")


if __name__ == "__main__":
    main()
